logging:
    level:
        root: info
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: debug
            hibernate:
                SQL: debug
                type: trace

                        
