logging:
    level:
        root: info
        # org:
        #     springframework:
        #         web:
        #             filter:
        #                 CommonsRequestLoggingFilter: debug
management:
  endpoints:
    web:
      base-path: /action_name
      exposure:
        include: health
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false