logging:
    level:
        root: debug
        # org:
        #     springframework:
        #         web:
        #             filter:
        #                 CommonsRequestLoggingFilter: debug
    # file:
    #     name: C:/dev/logs/was-log.log
                        
