logging:
    level:
        root: debug
    charset:
        console: utf-8    
        # org:
        #     springframework:
        #         web:
        #             filter:
        #                 CommonsRequestLoggingFilter: debug
    file:
        path: /project/logs/nuguProxyServer
    # charset:
    #     console: utf-8