logging:
    level:
        root: debug
    charset:
        console: utf-8    
        # org:
        #     springframework:
        #         web:
        #             filter:
        #                 CommonsRequestLoggingFilter: debug
    file:
        path: E:/dev/logs
    # charset:
    #     console: utf-8